# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b26bf3af816abde7458faa811e3f9739c83b55375bd665e484bfd57bcb1c35a5f2c9773e11bae6f57472249ae6973a1bf880b364c9056df5f7f5fd04d4345f78

test:
  secret_key_base: 3bd6537cea0ca834944f3441d10057b5d51702871d13dbb3a4f16b5016503acab9023d1fb44c79d75c972c22c6e0c567745eefc068978ccd804713201596ff15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
